modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "wagyourminimap"
version = "${version}"
displayName = "WagYourMinimap"
authors = "Wagyourtail"
description = '''
Minimap mod coded from scratch to not be ass.
'''
#logoFile = ""

[[dependencies.wagyourminimap]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3]"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.0,)"
ordering = "AFTER"
side = "BOTH"